UAIVeterinaria/Models/Owner.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using UAIVeterinaria.Interfaces;

namespace UAIVeterinaria.Models
{
    public partial class Owner : IEntity
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Address { get; set; }

        public ICollection<Pet> Pets { get; set; }
    }

    [MetadataType(typeof(OwnerMetadata))]
    public partial class Owner
    {
        public class OwnerMetadata
        {
            [Key]
            public int Id { get; set; }

            [StringLength(50)]
            [Required]
            public string Name { get; set; }

            [StringLength(50)]
            [Required]
            public string Surname { get; set; }

            [StringLength(50)]
            [Required]
            public string Address { get; set; }
        }
    }
}

UAIVeterinaria/Controllers/OwnerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UAIVeterinaria.Models;
using UAIVeterinaria.Data;

namespace UAIVeterinaria.Controllers
{
    public class OwnerController : Controller
    {
        OwnerRepository repo = new OwnerRepository();
        // GET: Owner
        public ActionResult Index()
        {
            return View(repo.List());
        }

        //GET: Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Owner owner)
        {
            repo.Insert(owner);
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var owner = repo.GetById(id);
            if (owner == null)
            {
                return HttpNotFound();
            }
            return View(owner);
        }

        [HttpPost]
        public ActionResult Edit(Owner owner)
        {
            repo.Update(owner);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            repo.Delete(id);
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            var owner = repo.GetById(id);
            if (owner == null)
            {
                return HttpNotFound();
            }
            return View(owner);
        }
    }
}

UAIVeterinaria/Controllers/PetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UAIVeterinaria.Data;
using UAIVeterinaria.Models;

namespace UAIVeterinaria.Controllers
{
    public class PetController : Controller
    {
        PetRepository repoPet = new PetRepository();
        OwnerRepository repoOwner = new OwnerRepository();

        // GET: Room
        public ActionResult Index()
        {
            return View(repoPet.List());
        }

        //GET: Create
        public ActionResult Create(int ownerId)
        {
            Pet pet = new Pet();
            pet.OwnerId = ownerId;
            pet.Owner = repoOwner.GetById(ownerId);
            return View(pet);
        }

        [HttpPost]
        public ActionResult Create(Pet pet)
        {
            repoPet.Insert(pet);
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var Pet = repoPet.GetById(id);
            if (Pet == null)
            {
                return HttpNotFound();
            }
            return View(Pet);
        }

        [HttpPost]
        public ActionResult Edit(Pet Pet)
        {
            repoPet.Update(Pet);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            repoPet.Delete(id);
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            var Pet = repoPet.GetById(id);
            if (Pet == null)
            {
                return HttpNotFound();
            }
            return View(Pet);
        }
    }
}

UAIVeterinaria/Views/Owner/Create.cshtml
@model UAIVeterinaria.Models.Owner

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Owner</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

UAIVeterinaria/Views/Owner/Details.cshtml
@model UAIVeterinaria.Models.Owner

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Owner</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Add Pet", "Create", "Pet", new { ownerId = Model.Id }, null) |
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

UAIVeterinaria/Views/Owner/Edit.cshtml
@model UAIVeterinaria.Models.Owner

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Owner</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

UAIVeterinaria/Views/Owner/Index.cshtml
@model IEnumerable<UAIVeterinaria.Models.Owner>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Surname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Surname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>